name: "build-test-pubtodockerhub"

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_run:
    workflows: 
      - Create Release
    types:
      - completed

jobs:
  build-test-pubtodockerhub:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion != 'failure' }}
    steps:


      - name: "Build: checkout source code"
        uses: actions/checkout@v2          
      - name: "Build: build docker image"
        run: |
          docker build --build-arg HASH=$GITHUB_SHA . -t localimage:latest


      - name: "Push: prepare version from git tags/branchs"
        id: docker_tag_meta
        uses: docker/metadata-action@v3
        with:
          images: abesesr/licencesnationales
      - name: "Push: login to DockerHub"
        if: github.event_name != 'pull_request'
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin  
      - name: "Push: push docker image"
        if: github.event_name != 'pull_request'
        run: |
          DOCKER_TAGS="${{ steps.docker_tag_meta.outputs.tags }}"
          for DOCKER_TAG in $DOCKER_TAGS
          do
            docker build . --target front-image -t ${DOCKER_TAG}-front
            docker push ${DOCKER_TAG}-front
          done
